{% set version = "4.0.1" %}

package:
  name: openslide
  version: {{ version }}

source:
  url: https://github.com/openslide/openslide/releases/download/v{{ version }}/openslide-{{ version }}.tar.xz
  sha256: df82f6b264f98d11eeb80d85bbb10c7935fcd69c7abae1d610ce49b9a0437faf

build:
  number: 0
  run_exports:
    # good compatibility in 3.X
    # https://abi-laboratory.pro/index.php?view=timeline&l=openslide
    - {{ pin_subpackage('openslide') }}

requirements:
  build:
    - meson
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
  host:
    - cairo
    # https://github.com/conda-forge/fontconfig-feedstock/issues/64
    - expat
    # https://github.com/conda-forge/fontconfig-feedstock/issues/64
    # (yes, same issue)
    - freetype
    - glib
    - libjpeg-turbo
    - openjpeg
    - libdicom
    # https://github.com/conda-forge/libxml2-feedstock/issues/164
    - liblzma-devel
    - libpng
    - libtiff
    - libxml2-devel
    - sqlite
    # https://github.com/conda-forge/xorg-libx11-feedstock/issues/51
    - xorg-xorgproto  # [linux]
    - zlib
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/libopenslide${SHLIB_EXT}  # [unix]
    - slidetool test deps  # [unix]
    - if not exist %LIBRARY_BIN%\libopenslide-1.dll exit 1   # [win]
    - '%LIBRARY_BIN%\slidetool.exe test deps'   # [win]

about:
  home: https://openslide.org/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: OpenSlide is a C library that provides a simple interface to read whole-slide images (also known as virtual slides).

extra:
  recipe-maintainers:
    - bgilbert
    - jcupitt
    - hmaarrfk
