{% set version = "3.4.1" %}

package:
  name: openslide
  version: {{ version }}

source:
  url: https://github.com/openslide/openslide/releases/download/v{{ version }}/openslide-{{ version }}.tar.gz
  sha256: fed08fab8a9b1ded95a34e196652291127ebe392c11f9bc13d26e760295a102d

build:
  number: 8
  skip: True  # [win]
  run_exports:
    # good compatibility in 3.X
    # https://abi-laboratory.pro/index.php?view=timeline&l=openslide
    - {{ pin_subpackage('openslide') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - make  # [unix]
    - {{ compiler('c') }}
    - pkg-config
  host:
    - cairo
    - cairo >=1.2
    - gdk-pixbuf
    - glib
    - glib >=2.48.0
    - libjpeg-turbo
    - openjpeg
    - openjpeg >=2.1
    - libpng
    - libtiff
    - libtiff >=4
    - libxml2
    - sqlite
    - sqlite >=3.6.2
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libopenslide${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\libopenslide.dll exit 1   # [win]

about:
  home: http://openslide.org/
  license: LGPL 2.1
  license_family: LGPL
  license_file: LICENSE.txt
  summary: OpenSlide is a C library that provides a simple interface to read whole-slide images (also known as virtual slides).

extra:
  recipe-maintainers:
    - jcupitt
    - hmaarrfk
