{% set version = "4.0.0" %}

package:
  name: openslide
  version: {{ version }}

source:
  url: https://github.com/openslide/openslide/releases/download/v{{ version }}/openslide-{{ version }}.tar.xz
  sha256: cc227c44316abb65fb28f1c967706eb7254f91dbfab31e9ae6a48db6cf4ae562
  patches:
    # https://github.com/openslide/openslide/pull/680
    - fix-win-build.patch
    - slidetool-unicode.patch
    # sqlite-feedstock builds SQLite with Makefile.msc on Windows, omitting
    # the pkg-config file
    # https://github.com/conda-forge/sqlite-feedstock/issues/131
    # https://github.com/openslide/openslide/pull/685
    - windows-find-sqlite3.patch
    # Produce the expected DLL name with clang
    # https://github.com/openslide/openslide/pull/686
    - windows-dll-name.patch

build:
  number: 3
  run_exports:
    # good compatibility in 3.X
    # https://abi-laboratory.pro/index.php?view=timeline&l=openslide
    - {{ pin_subpackage('openslide') }}

requirements:
  build:
    - meson
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
  host:
    - cairo
    - cairo >=1.2
    # https://github.com/conda-forge/fontconfig-feedstock/issues/64
    - expat
    - gdk-pixbuf
    - glib
    - glib >=2.56.0
    - libjpeg-turbo
    - openjpeg
    - openjpeg >=2.1
    - libdicom
    # https://github.com/conda-forge/libtiff-feedstock/issues/113
    - liblzma-devel
    - libpng
    - libtiff
    - libtiff >=4
    - libxml2
    - sqlite
    - sqlite >=3.14
    # https://github.com/conda-forge/xorg-libx11-feedstock/issues/51
    - xorg-xorgproto  # [linux]
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libopenslide${SHLIB_EXT}  # [unix]
    - env OPENSLIDE_DEBUG=synthetic slidetool prop list ""  # [unix]
    - if not exist %LIBRARY_BIN%\libopenslide-1.dll exit 1   # [win]

about:
  home: https://openslide.org/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: OpenSlide is a C library that provides a simple interface to read whole-slide images (also known as virtual slides).

extra:
  recipe-maintainers:
    - bgilbert
    - jcupitt
    - hmaarrfk
